version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    volumes:
      - .:/app
    command: npm run preview

  redis:
    image: "redis:7.0"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
