services:
  mailer-gui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUST_HOST=0.0.0.0
      - NUXT_PORT=3000
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    depends_on:
      - redis

  redis:
    image: "redis:7.4.2"
    ports:
      - "6379:6379"
